package constants

const PREPARE_TWO_NIGHT = "for 2 nights before and after"

const PREPARE_ONE_NIGHT = "for 1 night before & after"

const CHARGE_OPTION_REFERENCE = "charge_option_reference"

const CHARGE_TICKET_REFERENCE = "charge_ticket_reference"

const CHARGE_REFERENCE = "charge_reference"

const CODE_SCAN = "CODE_SCAN"

const OPTION_IS_VERIFIED = "OPTION_IS_VERIFIED"

const WEEKEND_PRICE = "WEEKEND_PRICE"

const BASE_PRICE = "BASE_PRICE"

const ADD_PRICE = "ADD_PRICE"

const ADD_DATE_FOUND = "ADD_DATE_FOUND"

const HOST_AS_INDIVIDUAL = "HOST_AS_INDIVIDUAL"

const PHOTOS = "PHOTOS"

const PUBLIC_PHOTOS = "PUBLIC_PHOTOS"

const COVER_IMAGE = "COVER_IMAGE"

const PUBLIC_COVER_IMAGE = "PUBLIC_COVER_IMAGE"

const TYPE_OF_SHORTLET = "TYPE_OF_SHORTLET"

const HOST_NAME = "HOST_NAME"

const HOST_JOINED = "HOST_JOINED"

const HOST_VERIFIED = "HOST_VERIFIED"

const CATEGORY = "CATEGORY"

const ALL_EXPERIENCE_CATEGORIES = "ALL_EXPERIENCE_CATEGORIES"

const EXPERIENCE = "EXPERIENCE"

const EXPERIENCE_OPTION_LOCATION = "EXPERIENCE_OPTION_LOCATION"

const EXPERIENCE_EVENT_LOCATION = "EXPERIENCE_EVENT_LOCATION"

const ALL_EXPERIENCE_LOCATION = "ALL_EXPERIENCE_LOCATION"

const EXPERIENCE_OPTION = "EXPERIENCE_OPTION"

const EXPERIENCE_EVENT = "EXPERIENCE_EVENT"

const TICKET_AVAILABLE = "TICKET_AVAILABLE"

const TICKET_LOWEST_PRICE = "TICKET_LOWEST_PRICE"

const EVENT_START_DATE = "EVENT_START_DATE"

const EVENT_END_DATE = "EVENT_END_DATE"

const LOCATION = "LOCATION"

const SUB_EVENT_TYPE = "SUB_EVENT_TYPE"

const HAS_FREE_TICKET = "HAS_FREE_TICKET"
