package constants

// const USERNAME = "USERNAME"
const PASSWORD = "PASSWORD"
const EMAIL = "EMAIL"
const FIRSTNAME = "FIRSTNAME"
const LASTNAME = "LASTNAME"
const PHONE_NUMBER = "PHONE_NUMBER"

// const PHONE_NUMBER_CODE = "PHONE_NUMBER_CODE"
// const DIAL_CODE_NUMBER = "DIAL_CODE_NUMBER"
// const DIAL_COUNTRY = "DIAL_COUNTRY"
const CODE_CONFIRMED = "CODE_CONFIRMED"

const PROFILE_PHOTO = "PROFILE_PHOTO"

const PUBLIC_PROFILE_PHOTO = "PUBLIC_PROFILE_PHOTO"

//const USER_ID = "USER_ID"

const OPTION_CONN_USERNAME = "OPTION_CONN_USERNAME"
const SHORTLET_INDEX_DB = "SHORTLET_INDEX_DB"
const SHORTLET_INDEX_REDIS = "SHORTLET_INDEX_REDIS"
const SHORTLET_USED_REDIS = "SHORTLET_USED_REDIS"
const SHORTLET_USED_DB = "SHORTLET_USED_DB"

const GET_ALL_OPTIONS_ROUTE_ID = "GET_ALL_OPTIONS_ROUTE_ID"

const TO_EMAIL = "TO_EMAIL"

// const EMAIL_NUMBER_CODE = "EMAIL_NUMBER_CODE"
const FROM_EMAIL = "FROM_EMAIL"

const NONE = "none"

//const HANDLE_PHONE_VERIFY = "HANDLE_PHONE_VERIFY"
//const GRID_EMAIL_VERIFY = "GRID_EMAIL_VER"
