// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: event_check_in_steps.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEventCheckInStep = `-- name: CreateEventCheckInStep :one
INSERT INTO event_check_in_steps (
        event_date_time_id,
        photo,
        des
    )
VALUES (
        $1, $2, $3
    )
RETURNING id, event_date_time_id, photo, des, created_at, updated_at
`

type CreateEventCheckInStepParams struct {
	EventDateTimeID uuid.UUID `json:"event_date_time_id"`
	Photo           string    `json:"photo"`
	Des             string    `json:"des"`
}

func (q *Queries) CreateEventCheckInStep(ctx context.Context, arg CreateEventCheckInStepParams) (EventCheckInStep, error) {
	row := q.db.QueryRow(ctx, createEventCheckInStep, arg.EventDateTimeID, arg.Photo, arg.Des)
	var i EventCheckInStep
	err := row.Scan(
		&i.ID,
		&i.EventDateTimeID,
		&i.Photo,
		&i.Des,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventCheckInStep = `-- name: GetEventCheckInStep :one
SELECT des, photo
FROM event_check_in_steps
WHERE id = $1 AND event_date_time_id=$2
`

type GetEventCheckInStepParams struct {
	ID              uuid.UUID `json:"id"`
	EventDateTimeID uuid.UUID `json:"event_date_time_id"`
}

type GetEventCheckInStepRow struct {
	Des   string `json:"des"`
	Photo string `json:"photo"`
}

func (q *Queries) GetEventCheckInStep(ctx context.Context, arg GetEventCheckInStepParams) (GetEventCheckInStepRow, error) {
	row := q.db.QueryRow(ctx, getEventCheckInStep, arg.ID, arg.EventDateTimeID)
	var i GetEventCheckInStepRow
	err := row.Scan(&i.Des, &i.Photo)
	return i, err
}

const listEventCheckInStepOrdered = `-- name: ListEventCheckInStepOrdered :many
SELECT des, photo, id
FROM event_check_in_steps
WHERE event_date_time_id = $1
ORDER BY created_at
`

type ListEventCheckInStepOrderedRow struct {
	Des   string    `json:"des"`
	Photo string    `json:"photo"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) ListEventCheckInStepOrdered(ctx context.Context, eventDateTimeID uuid.UUID) ([]ListEventCheckInStepOrderedRow, error) {
	rows, err := q.db.Query(ctx, listEventCheckInStepOrdered, eventDateTimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventCheckInStepOrderedRow{}
	for rows.Next() {
		var i ListEventCheckInStepOrderedRow
		if err := rows.Scan(&i.Des, &i.Photo, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCheckInStepPhotos = `-- name: ListEventCheckInStepPhotos :many
SELECT photo
FROM event_check_in_steps
WHERE event_date_time_id = $1
ORDER BY created_at
`

func (q *Queries) ListEventCheckInStepPhotos(ctx context.Context, eventDateTimeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventCheckInStepPhotos, eventDateTimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var photo string
		if err := rows.Scan(&photo); err != nil {
			return nil, err
		}
		items = append(items, photo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllEventCheckInStep = `-- name: RemoveAllEventCheckInStep :exec
DELETE FROM event_check_in_steps 
WHERE event_date_time_id = $1
`

func (q *Queries) RemoveAllEventCheckInStep(ctx context.Context, eventDateTimeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllEventCheckInStep, eventDateTimeID)
	return err
}

const removeEventCheckInStep = `-- name: RemoveEventCheckInStep :exec
DELETE FROM event_check_in_steps 
WHERE event_date_time_id = $1 AND id = $2
`

type RemoveEventCheckInStepParams struct {
	EventDateTimeID uuid.UUID `json:"event_date_time_id"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) RemoveEventCheckInStep(ctx context.Context, arg RemoveEventCheckInStepParams) error {
	_, err := q.db.Exec(ctx, removeEventCheckInStep, arg.EventDateTimeID, arg.ID)
	return err
}

const updateEventCheckInStepDes = `-- name: UpdateEventCheckInStepDes :one
UPDATE event_check_in_steps
    SET des = $1, 
    updated_at = NOW()
WHERE id = $2 AND event_date_time_id = $3
RETURNING des, photo, id
`

type UpdateEventCheckInStepDesParams struct {
	Des             string    `json:"des"`
	ID              uuid.UUID `json:"id"`
	EventDateTimeID uuid.UUID `json:"event_date_time_id"`
}

type UpdateEventCheckInStepDesRow struct {
	Des   string    `json:"des"`
	Photo string    `json:"photo"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEventCheckInStepDes(ctx context.Context, arg UpdateEventCheckInStepDesParams) (UpdateEventCheckInStepDesRow, error) {
	row := q.db.QueryRow(ctx, updateEventCheckInStepDes, arg.Des, arg.ID, arg.EventDateTimeID)
	var i UpdateEventCheckInStepDesRow
	err := row.Scan(&i.Des, &i.Photo, &i.ID)
	return i, err
}

const updateEventCheckInStepPhoto = `-- name: UpdateEventCheckInStepPhoto :one
UPDATE event_check_in_steps
    SET photo = $1, 
    updated_at = NOW()
WHERE id = $2 AND event_date_time_id = $3
RETURNING des, photo, id
`

type UpdateEventCheckInStepPhotoParams struct {
	Photo           string    `json:"photo"`
	ID              uuid.UUID `json:"id"`
	EventDateTimeID uuid.UUID `json:"event_date_time_id"`
}

type UpdateEventCheckInStepPhotoRow struct {
	Des   string    `json:"des"`
	Photo string    `json:"photo"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEventCheckInStepPhoto(ctx context.Context, arg UpdateEventCheckInStepPhotoParams) (UpdateEventCheckInStepPhotoRow, error) {
	row := q.db.QueryRow(ctx, updateEventCheckInStepPhoto, arg.Photo, arg.ID, arg.EventDateTimeID)
	var i UpdateEventCheckInStepPhotoRow
	err := row.Scan(&i.Des, &i.Photo, &i.ID)
	return i, err
}
