// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: event_reference_infos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEventReferenceInfo = `-- name: CreateEventReferenceInfo :exec
INSERT INTO event_reference_infos (
    event_charge_id,
    event_date_location,
    event_info, 
    event_date_times,
    event_date_details,
    host_as_individual,
    cancel_policy_one,  
    cancel_policy_two,
    organization_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateEventReferenceInfoParams struct {
	EventChargeID     uuid.UUID `json:"event_charge_id"`
	EventDateLocation string    `json:"event_date_location"`
	EventInfo         string    `json:"event_info"`
	EventDateTimes    string    `json:"event_date_times"`
	EventDateDetails  string    `json:"event_date_details"`
	HostAsIndividual  bool      `json:"host_as_individual"`
	CancelPolicyOne   string    `json:"cancel_policy_one"`
	CancelPolicyTwo   string    `json:"cancel_policy_two"`
	OrganizationName  string    `json:"organization_name"`
}

func (q *Queries) CreateEventReferenceInfo(ctx context.Context, arg CreateEventReferenceInfoParams) error {
	_, err := q.db.Exec(ctx, createEventReferenceInfo,
		arg.EventChargeID,
		arg.EventDateLocation,
		arg.EventInfo,
		arg.EventDateTimes,
		arg.EventDateDetails,
		arg.HostAsIndividual,
		arg.CancelPolicyOne,
		arg.CancelPolicyTwo,
		arg.OrganizationName,
	)
	return err
}
