// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: report_options.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReportOption = `-- name: CreateReportOption :exec
INSERT INTO report_options (
    option_user_id,
    user_id,
    type_one,
    type_two,
    type_three,
    description
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReportOptionParams struct {
	OptionUserID uuid.UUID `json:"option_user_id"`
	UserID       uuid.UUID `json:"user_id"`
	TypeOne      string    `json:"type_one"`
	TypeTwo      string    `json:"type_two"`
	TypeThree    string    `json:"type_three"`
	Description  string    `json:"description"`
}

func (q *Queries) CreateReportOption(ctx context.Context, arg CreateReportOptionParams) error {
	_, err := q.db.Exec(ctx, createReportOption,
		arg.OptionUserID,
		arg.UserID,
		arg.TypeOne,
		arg.TypeTwo,
		arg.TypeThree,
		arg.Description,
	)
	return err
}
