FROM nginx:1.23.3-alpine


COPY ./flizzup-server_com.crt /etc/nginx/conf.d/certs/flizzup-server_com.crt
COPY ./flizzup-server_com.pem /etc/nginx/conf.d/certs/flizzup-server_com.pem
COPY ./default.conf /etc/nginx/conf.d/default.conf



