package algo

var concert = []string{"Thrilling", "Captivating", "Chorus", "Trumpet", "Percussion", "Conductor", "Ensemble", "Harmonious", "Keyboard", "Lively", "Instrumentals", "Electric", "Setlist", "Open-air", "Intimate", "Rehearsal", "Duet", "Iconic", "Bass", "Music", "Memorable", "Enchanting", "Melody", "Acoustic", "Hymn", "Amphitheater", "Electricity", "Concertgoers", "Arena", "Rhythm", "Energetic", "Woodwinds", "Tickets", "Performer", "Solo", "Strings", "Artist", "Impressive", "Stagecraft", "Live", "Jazz", "Jam Session", "Epic", "Atmosphere", "Pop", "Fusion", "Choreography", "Drums", "Vibrant", "Indoor", "Headliner", "Melodic", "Fan", "Hype", "Venue", "Synthesizer", "Concert Hall", "Horns", "Singer", "Backing", "Curtain", "Vocals", "Supporting", "Stadium", "Synchronized", "Amplifiers", "Audience", "Harmony", "Euphoria", "Ticket Sales", "Guitar", "Violin", "Classical", "Lights", "Show", "Sound", "Soulful", "Backstage", "Magical", "Unforgettable", "Dynamic", "Band", "Brass", "Rock", "Playlist", "Encore", "Piano", "Beat", "Saxophone", "Greatest Hits"}

var partyAndGathering = []string{"Soho", "Mirth", "Themed Party", "Blowout", "Company Retreat", "Bachelorette Party", "Theme Park Party", "Milestone Celebration", "Dinner Party", "Afterparty", "Sweet Sixteen Party", "Revels", "Socializing", "Beach Party", "Happening", "Spree", "Launch Party", "Gathering", "Frolic", "Tear", "Welcome Party", "Knees-up", "Caper", "Outdoor Party", "Block Party", "Bachelor Party", "Nightlife", "Pleasure", "Merrymaking", "Conviviality", "Gayety", "Rooftop Party", "Jubilee", "Holiday Party", "Pub Crawl", "Feast", "House Party", "Gambol", "Romp", "Hootenanny", "Gala", "Fiesta", "DJ Party", "Engagement Celebration", "Graduation Party", "Corporate Party", "Engagement Party", "Revelry", "Regale", "Indoor Party", "Quinceañera", "Neighborhood Gathering", "Cocktail Party", "Office Party", "Masquerade", "Maffick", "Get-together", "Blast", "Children's Party", "High School Reunion", "Ball", "Commemoration", "Jamboree", "Pool Party", "Wine Tasting", "BBQ Party", "Charity Gala", "Social", "Themed Costume Party", "Socialize", "Clubbing", "Wedding Celebration", "VIP Party", "Bacchanalia", "Festivity", "Fundraiser", "Catered Event", "Cavort", "Jollification", "Soiree", "Fling", "Splurge", "Roister", "Bender", "Retirement Party", "Function", "Buffet", "Costume Party", "Reunion", "Beer Bash", "Surprise Party", "Shivoo", "Swaray", "Gaiety", "Garden Party", "Farewell Party", "Merriment", "Graduation Celebration", "Rejoice", "Rejoicing", "Fête", "Rave", "Team Building", "Shindig", "Good Times", "Birthday Party", "Holiday Celebration", "Party", "Hooley", "Bacchanal", "Carousing", "Splash", "Carousal", "Convivial", "Gala Dinner", "Frolics", "Banquet", "Frolicsome", "Escapade", "Family Reunion", "Exclusive Event", "Anniversary Party", "Live Music", "Bash", "Rendezvous", "Wedding Reception", "Revel", "Sociable", "Affair", "Bachelor/Bachelorette Weekend"}

var shows = []string{"Art Installation", "Melodrama Performance", "Highwire", "Operetta Performance", "Outdoor Theater", "Stunts", "Dance Performance", "Street Performers", "Operetta", "Live Performance", "Circus Performance", "Cabaret Performance", "Play", "Energetic Show", "Art Gallery", "Music Theater", "Fireworks", "Dramatic Performance", "Burlesque", "Magic", "Variety Show", "Tribute Band", "Side Show", "Pantomime", "Open-air Performance", "Magic Show", "Cabaret", "Unforgettable Show", "Performance Group", "Ballet", "Comedy Show", "Circus", "Shakespearean Play", "Captivating Show", "Laser Show", "Art Exhibition", "Live Band", "Revue Show", "Thrilling Show", "Stand-up", "Sculpture", "Trapeze", "Children's Theater", "Concert Series", "Improvisational Comedy", "Pantomime Show", "Memorable Show", "Cirque", "Painting", "Dance", "Choir", "Opera", "Stage Show", "Theatrical Comedy", "Burlesque Show", "Big Top", "Melodrama", "Dramatic Show", "Act", "Black Box Theater", "Improv", "Conjuring", "Magical Show", "Ballet Performance", "Ice Skating", "Musical Revue", "Vaudeville", "Illusion Show", "Variety", "Ringmaster", "Acrobatics", "Tragedy", "Juggling", "A Cappella", "Theatrical", "Vaudeville Performance", "Contortionist", "Street Magic", "Card Tricks", "Ice Skating Show", "Circus Acts", "Production", "Revue", "Light Show", "Illusion", "Enchanting Show", "Community Theater", "Animal Acts", "Spectacular Show", "Mesmerizing Show", "Sound and Light", "Opera Performance"}

var praiseJam = []string{"Divine Music Showcase", "Soulful Singing Contest", "Soul-Stirring Music Festival", "Hymn Singing Contest", "Praise and Worship Seminar", "Faith Music Symposium", "Praise and Worship Gathering", "Gospel Music Symposium", "Sacred Music Event", "Sacred Music Concert", "Sacred Music Workshop", "Gospel Acoustic Showcase", "Christian Music Festival", "Spiritual Singing Contest", "Divine Melodies Concert", "Christian Songwriters' Festival", "Worshipful Music Revival", "Worshipful Music Gathering", "Gospel Music Festival", "Prayerful Music Event", "Inspirational Music Symposium", "Heavenly Voices Concert", "Gospel Concert", "Worshipful Music Seminar", "Anointed Singing Contest", "Holy Music Concert", "Gospel Jam Session", "Gospel Music Extravaganza", "Worshipful Music Workshop", "Prayer and Praise Session", "Spirit-Filled Concert", "Praise Fest", "Spiritual Music Jam", "Praise and Worship Revival", "Christian Music Concert", "Inspirational Music Retreat", "Anointed Worship Night", "Soul-Stirring Performance", "Gospel Music Workshop", "Praise and Worship Spectacle", "Sacred Music Jam Session", "Worship Experience", "Christian Music Symposium", "Prayerful Music Showcase", "Faith Music Spectacle", "Gospel Music Jamboree", "Christian Songwriters' Showcase", "Hymn Singing", "Devotional Song Night", "Devotional Music Gathering", "Praise and Worship Marathon", "Worshipful Singing Contest", "Praise and Worship Retreat", "Spirit-Filled Worship Night", "Christian Music Revival", "Gospel Music Gala", "Spiritual Celebration", "Worshipful Concert", "Devotional Music Concert", "Religious Music Performance", "Spiritual Music Symposium", "Gospel Acoustic Jam", "Inspiring Music Festival", "Gospel Music Open Mic", "Inspirational Music Night", "Gospel Music Marathon", "Gospel Choir Showcase", "Faith-based Concert", "Divine Melodies Showcase", "Gospel Music Seminar", "Christian Music Carnival", "Soulful Concert", "Sacred Music Revival", "Prayerful Music Revival", "Soulful Music Concert", "Inspirational Music Jam", "Christian Music Gala", "Spiritual Singing Showcase", "Faith Music Concert", "Gospel Singing Contest", "Gospel Music Showcase", "Spirit-Filled Singing Contest", "Gospel Music Retreat", "Holy Music Showcase", "Christian Songwriters' Retreat", "Spiritual Music Festival", "Heavenly Voices Showcase", "Worship Night"}

var productLaunch = []string{"Expo", "Upgrade", "Publishing", "Specifications", "Launching", "Storefront", "Announcement", "Booth", "Distributing", "Review", "Advertising", "Breakthrough", "Promotion", "Unveiling", "Activation", "Features", "Release", "Integration", "Initiating", "Introduction", "Pop-up", "Testing", "Roadshow", "Unboxing", "Commencing", "Unleashing", "Demo", "Demonstration", "Exhibit", "Rollout", "Stand", "Reveal", "Trade Show", "Evaluation", "Debut", "Comparison", "Demonstrating", "Showcasing", "Benefits", "Launchpad", "Launch", "Embarking", "Kickoff", "Feedback", "Open House", "Branding", "Campaign", "Congress", "Summit", "Preview"}
var competition = []string{"Triathlon", "Combat", "Marathon", "Baseball", "Cricket", "Sportsmen", "Bodybuilding", "Finals", "Bout", "Powerlifting", "Diving", "Defeat", "Relay", "Polo", "Face-off", "Hurdles", "Leagues", "Skirmish", "Conflict", "Prize", "Canoeing", "Golf", "Football", "Trohpy", "Protagonists", "Tennis", "Taekwondo", "Game", "Contest", "Sprint", "Warfare", "Showdown", "Eliminations", "Opponents", "Skateboarding", "Confrontation", "Record", "Qualifiers", "Contestants", "Auto Racing", "Sports", "Winner", "Shooting", "Finalists", "Struggle", "Challengers", "Ice Hockey", "Fencing", "Awards", "Wrestling", "Motorcross", "Encounter", "Squads", "Basketball", "Sportswomen", "Trial", "Gymnastics", "Clash", "Rivals", "Scrimmage", "Contend", "Cycle", "Runner-up", "Softball", "Contenders", "Run", "Duels", "Boxing", "Rivalry", "Soccer", "Trials", "Adversaries", "Participants", "Horse Racing", "Medals", "Weightlifting", "Competitors", "Match", "Title", "Rugby", "Derby", "Battle", "Volleyball", "Karate", "Teams", "Athletes", "Rowing", "Tournament", "Athletics", "Judo", "Olympics", "Swim", "Archery"}

var class = []string{"Session", "Acquisition", "Academy", "License", "Student", "Subject", "Advanced", "Development", "Mastery", "Capability", "Skill-building", "Education", "Series", "Registration", "Scholar", "Apprentice", "Study", "Skillset", "Novice", "Beginner", "Qualification", "Online", "Tutorial", "Enrichment", "Learner", "Growth", "Personal", "Practice", "Lesson", "Participant", "Skills", "Insight", "Application", "Awareness", "Competence", "Intermediate", "Diploma", "Curriculum", "Bootcamp", "Mentoring", "Advancement", "Knowledge", "Refinement", "Module", "Progress", "Familiarity", "Hybrid", "Remote", "Pupil", "Topic", "Competencies", "Improvement", "Certification", "Virtual", "In-person", "Degree", "Trainee", "Self-improvement", "Attendee", "Competency", "Understanding", "Specialization", "Enrollment", "Classroom", "Accreditation", "Instruction", "Coaching", "Tuition", "Proficiency", "Intensive", "Expertise"}

var movie = []string{"Picture", "Oscars", "Family", "Cineplex", "Adaptation", "Red Carpet", "Cinematic", "Golden Globe", "Cinematic Experience", "Sci-fi", "Film", "Fantasy", "Screenplay", "Art-house", "Casting", "Feature", "Foreign", "War", "Film Noir", "Sequel", "Movie", "Flick", "Technicolor", "IMAX", "Film Festival", "Actor", "Screen", "Trilogy", "Franchise", "Thriller", "Cult Classic", "Remake", "Indie", "Multiplex", "Film Buff", "Dialogue", "Special Effects", "Mystery", "Romance", "Plot", "Projector", "Cinematography", "Producer", "History", "Western", "Chart-topper", "Editing", "Soundtrack", "Matinee", "Black and White", "Showing", "Cinematic Universe", "Filmography", "Score", "Live-action", "Action", "Biography", "Cinema", "Crime", "Moviegoer", "Concession", "Big Screen", "Opening Night", "Celluloid", "Documentary", "Box Office", "3D", "Period", "Sport", "Popcorn", "Mainstream", "Actress", "Smash", "Reel", "Director", "Motion Picture", "Character", "Cinephile", "Blockbuster", "Horror", "Motion Film", "Silent", "Moving Image", "Animation", "Ticket", "Hit", "Screening", "Silver Screen", "Projection", "Cannes", "Animated", "Script"}

var rally = []string{"Codriver", "Rally Stage", "Rallycross", "Endurance Racing", "Off-road Adventure", "Focus", "Auto", "Team", "Off-road Racing", "Challenger", "Driver", "Excitement", "Track", "Endurance", "Handling", "Pit Stop", "Cross Country Rally", "Ice", "Precision", "Amateur", "Rally Raid", "Rally Team", "Service Area", "Navigator", "Route", "Acceleration", "Motorsport", "Terrain", "Braking", "Machine", "Stamina", "Admirers", "Rally Driver", "Vehicle", "Adrenaline", "Mechanics", "Snow", "Forest", "Control", "Speed Test", "Stage Rally", "Off-road Excursion", "Engine", "Racecourse", "Gravel Racing", "Car", "Thrill", "Time Challenge", "Spectator", "Fans", "Map", "Gravel", "Rallying", "Time Trial", "Rally Racing", "Mountain", "Checkpoint", "Mud", "Experience", "Racing Series", "Instructions", "Trophy", "Enthusiasts", "Roadbook", "Special Stage", "Competition", "Technical", "Timed Section", "Waypoints", "Speed", "Co-driver", "Power", "Navigation", "Dirt", "Refueling", "Tire Change", "Win"}

var excursion = []string{"Escape", "Camping Trip", "Cruise Excursion", "Scuba Diving", "Rafting", "Botanical Garden Visit", "Discovery", "Sightseeing", "Sightseeing Excursion", "Walking Tour", "Resort Stay", "Landmark Visit", "Wildlife Safari", "Backpacking", "Garden Tour", "Hot Air Balloon Ride", "Roaming", "Ecotourism", "Visit", "Fishing Trip", "Heritage Tour", "Hiking", "Scenic Drive", "Sunrise Watching", "Trip", "Meditation Retreat", "Camping", "Cultural Tour", "Excursion", "Mountain Climbing", "Zoo Visit", "Winery Tour", "Expedition", "Road Trip", "Stargazing", "Outing", "Sunset Watching", "Sustainable Travel", "Photography Expedition", "Snorkeling", "Rejuvenation", "Theme Park Visit", "Nature Walk", "Voyage", "Food Festival", "Beach Vacation", "Relaxation", "Horseback Riding", "Field Trip", "Helicopter Tour", "Guided Tour", "Exploration", "Leisure", "Water Sports", "Island Hopping", "Theater Visit", "City Tour", "Mountain Retreat", "National Park Visit", "Bicycle Tour", "Cruise", "Day Trip", "Parade", "Art Gallery Visit", "Getaway", "Cultural Festival", "Travel", "Pilgrimage", "Boat Trip", "Picnic", "Biking", "Archaeological Tour", "Journey", "Museum Visit", "Historical Tour", "Culinary Tour", "Jaunt", "Monument Visit", "Spa Retreat", "Environmental Conservation", "Adventure Sports", "Wellness Retreat", "Yoga Retreat", "Amusement Park Visit", "Campfire"}

var seminar = []string{"Engaging", "Public Speaking", "Trends and Predictions", "Networking Opportunities", "Teamwork", "Speech", "Motivational", "Thought-provoking", "Speaker", "Inspiring Stories", "Case Studies", "Technology", "Problem Solving", "Design Thinking", "Enlightening", "Enriching", "Research Findings", "Panel", "Interactive", "Instructive", "Ethics", "Industry Trends", "Leadership Development", "Inspirational", "Motivation", "Science", "Educative", "Sales", "Sustainability", "Best Practices", "Management", "Colloquium", "Blockchain", "Social Media", "Diversity and Inclusion", "Knowledge Sharing", "Keynote", "Artificial Intelligence", "Communication", "Digital Transformation", "Collaboration", "Expert", "Innovative Strategies", "Critical Thinking", "Data Analytics", "Emerging Technologies", "Personal Growth", "Discussion", "Leadership", "Educational", "Meeting", "Change Management", "Thought Leadership", "Panel Discussion", "Career Development", "Insightful", "Informative", "Wellness", "Globalization", "Industry", "Environmental", "Creativity", "Finance", "Customer Experience", "Academic", "Instructor", "Interactive Sessions", "Cultural Awareness", "Cybersecurity", "Project Management", "Agile Methodology", "Business", "Practical Tips", "Career Advancement", "Time Management", "Talk", "Entrepreneurship", "Facilitator", "Empowering", "Health", "Cloud Computing", "Success Stories", "Productivity", "Goal Setting", "Transformative", "Professional Skills", "Professional Development", "Trainer", "Expert Insights", "Research"}

var eventDes = map[string][]string{"concert": concert, "party_and_gathering": partyAndGathering, "shows": shows, "praise_jam": praiseJam, "product_launch": productLaunch, "competition": competition, "class": class, "movie": movie, "rally_race": rally, "event_tour": excursion, "seminar": seminar}

// Highlight

var concertHigh = []string{"all_night_performance"}
var partyAndGatheringHigh = []string{"history", "party_with_drinks", "contest"}
var showsHigh = []string{"fashion_show", "product_release", "art"}

//var seminarHigh = []string{"history", "art", "talk", "inspiring"}
var praiseJamHigh = []string{"fellowship"}
var productLaunchHigh = []string{"product_release", "talk", "inspiring", "art", "history"}
var competitionHigh = []string{"contest", "game_fest", "racing", "history"}
var classHigh = []string{"gain_skill", "history", "tech_like"}
var movieHigh = []string{"movie_night"}
var excursionHigh = []string{"history", "art", "product_release"}
var rallyHigh = []string{"racing", "all_night_performance", "inspiring", "unique"}
var seminarHigh = []string{"history", "art", "inspiring", "talk"}

var eventHighlight = map[string][]string{"concert": concertHigh, "party_and_gathering": partyAndGatheringHigh, "shows": showsHigh, "praise_jam": praiseJamHigh, "product_launch": productLaunchHigh, "competition": competitionHigh, "class": classHigh, "movie": movieHigh, "rally_race": rallyHigh, "event_tour": excursionHigh, "seminar": seminarHigh}

// Main type

var concertType = []string{"concert_show"}
var partyAndGatheringType = []string{"party_gathering"}
var showsType = []string{"concert_show"}

//var seminarType = []string{"history", "art", "talk", "inspiring"}
var praiseJamType = []string{"concert_show"}
var productLaunchType = []string{"product_launch"}
var competitionType = []string{"competition"}
var classType = []string{"event_class"}
var movieType = []string{"concert_show", "party_gathering"}
var seminarType = []string{"seminar_talk"}
var excursionType = []string{"event_tour"}
var rallyType = []string{"rally_race"}

var eventType = map[string][]string{"concert": concertType, "party_and_gathering": partyAndGatheringType, "shows": showsType, "praise_jam": praiseJamType, "product_launch": productLaunchType, "competition": competitionType, "class": classType, "movie": movieType, "rally_race": rallyType, "event_tour": excursionType, "seminar": seminarType}

// Sub type
var concertSubType = []string{"musical_concert"}
var partyAndGatheringSubType = []string{"art_display", "house_party", "pool_party", "beach_party", "beach_party", "charity_cause", "game_night", "history_discussion", "community_culture", "social_media_and_influencing", "beauty", "climate_and_world_change", "camping", "guinness_world_record"}
var showsSubType = []string{"dance", "comedy_night", "fashion_show", "fashion", "guinness_world_record", "science_and_technology", "car", "gaming"}
var praiseJamSubType = []string{"praise_jam"}
var productLaunchSubType = []string{"car", "science_and_technology", "gaming", "fashion", "art"}
var competitionSubType = []string{"sports", "eduction", "motor_racing", "fashion", "art", "gaming", "drama", "musical"}
var classSubType = []string{"history_discussion", "social_media_and_influencing", "beauty", "climate_and_world_change", "fishing", "animal_certified_haunting", "dance", "sport_and_fitness", "culture", "language", "gaming", "politics", "health_and_wellness", "history", "fine_arts", "cooking", "drama_and_acting"}
var movieSubType = []string{"movie_night", "live_theatre_play"}
var seminarSubType = []string{"history_discussion", "community_culture", "social_media_and_influencing", "beauty", "climate_and_world_change", "sport_and_fitness", "health_and_wellness", "science_and_technology", "travel_and_outdoor", "fashion", "charity_cause", "art", "gaming", "beauty", "conference", "government_and_politics"}
var excursionSubType = []string{"art_and_museum", "zoo", "fashion", "art_gallery", "science_and_technology", "stadium", "school", "sport_club", "house", "estate", "hotel", "restaurant", "club", "building", "conference"}
var rallySubType = []string{"motorsport_racing", "road_rallies", "touring_assembly", "bike_racing", "rallycross", "motor_bike_racing"}

var eventSubType = map[string][]string{"concert": concertSubType, "party_and_gathering": partyAndGatheringSubType, "shows": showsSubType, "praise_jam": praiseJamSubType, "product_launch": productLaunchSubType, "competition": competitionSubType, "class": classSubType, "movie": movieSubType, "rally_race": rallySubType, "event_tour": excursionSubType, "seminar": seminarSubType}

var EventCategory = []string{"concert", "party_and_gathering", "shows", "praise_jam", "product_launch", "competition", "class", "movie", "rally_race", "event_tour", "seminar"}
